### ISSUE TITLE
大佬，能否实现弹出来直接是机型确认后的第二个页面呢？会快很多

### ISSUE THREAD

**Issue by Nerfixxxx000** [azhan1998/apple-store-helper_ForZhMo#2]
大佬，现在澳门不用短信，如果能提前设置好要填入和选择的信息，有货直接第二部能自己填充确认就完美了，实现全自动，不知道有没有实现的可能呢？

**Comment by azhan1998** [comment]
sorry我也是二把刀的水平，水平有限目前没精力继续优化~ thanks your star!
