### ISSUE TITLE
你好，请问怎么运行？

### ISSUE THREAD

**Issue by daysonC** [azhan1998/apple-store-helper_ForZhMo#4]

**Comment by azhan1998** [comment]
download and build

**Comment by daysonC** [comment]
哥们儿，澳门现在又要短信了，您现在这个版本貌似不工作了

**Comment by azhan1998** [comment]
我手机在手里了，我不管

**Comment by azhan1998** [comment]
不为黄牛倒爷工作

**Comment by daysonC** [comment]
天啊！好快！都什么时候了黄牛倒爷早收工了啊。。。
20号守到现在了。。。

**Comment by azhan1998** [comment]
不如让我给你推个倒爷。。。 code好久不看了，你可以试着更新一下。难度不大

**Comment by daysonC** [comment]
这么多年的苹果都是直营店买的，能快就快，不行就想办法快了

您教的downloadBuild，我倒腾了1天才run起来，还问了几路人。。。o(*￣︶￣*)o

什么更新什么修改就更不会了，天书

**Comment by daysonC** [comment]
我就想着自己手已经很快了，怎么就是不行，短信费浪费了不少，

指点一下吧大佬

**Comment by daysonC** [comment]
code是啥。。。鹅叫。。。

**Comment by azhan1998** [comment]
代购费一共200-300吧好像，现在便宜了 可能100？

**Comment by azhan1998** [comment]
黄牛有全自动的，因为没库存了 所以你抢不到

**Comment by azhan1998** [comment]
qq 504860058
